---
all:
    hosts:
        vpn-server:
            ansible_user: ubuntu
            ansible_host: 35.184.106.139
            ansible_port: 22
        rasp:
            ansible_user: pi
            ansible_host: raspberrypi.local
            ansible_port: 22